Bootstrap: localimage
From: sequana.img

%labels
    Author thomas cokelaer
    Version v1.0


%post

    export PATH=$PATH:/usr/local/anaconda/bin
    export LANG=C   # prevents perl for raising warnings
    export PERL5LIB=/usr/local/anaconda/lib/perl5/5.22.0

    git clone git://github.com/sequana/sequana_demultiplex.git
    cd sequana_demultiplex
    python setup.py install


